# Generated by Django 4.0.4 on 2022-05-22 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Удалено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Нововсть')),
                ('description_as_markdown', models.BooleanField(default=True, verbose_name='Маркдаун')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('cover', models.CharField(default='No image', max_length=124, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Удалено')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('preambule', models.CharField(max_length=2255, verbose_name='Превью')),
                ('body', models.TextField(verbose_name='Новость')),
                ('body_as_markdown', models.BooleanField(default=False, verbose_name='Маркдаун')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Удалено')),
                ('num', models.PositiveIntegerField(verbose_name='Номер урока')),
                ('title', models.CharField(max_length=50, verbose_name='Название урока')),
                ('description', models.CharField(max_length=255, verbose_name='Описание урока')),
                ('description_as_markdown', models.BooleanField(default=False, verbose_name='Маркдаун')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.courses')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['course', 'num'],
            },
        ),
        migrations.CreateModel(
            name='CourseTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Удалено')),
                ('name_first', models.CharField(max_length=100, verbose_name='Имя')),
                ('name_second', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('day_birth', models.DateField(verbose_name='День рождения')),
                ('course', models.ManyToManyField(to='mainapp.courses')),
            ],
            options={
                'verbose_name': 'Препоаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
