# Generated by Django 4.0.4 on 2022-05-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_courses_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created', 'title'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='courseteachers',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='courseteachers',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
