# Generated by Django 4.0.4 on 2022-05-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_news_options_rename_created_at_courses_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseteachers',
            name='created',
        ),
        migrations.RemoveField(
            model_name='courseteachers',
            name='updated',
        ),
    ]
