# Generated by Django 4.0.4 on 2022-05-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_courseteachers_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='deleted_at',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='deleted_at',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='deleted_at',
            new_name='deleted',
        ),
    ]
